// <auto-generated />
using System;
using EGM.GQL.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EGM.GQL.DataAccess.Migrations
{
    [DbContext(typeof(GraphyDbContext))]
    partial class GraphyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("EGM.GQL.DataAccess.Abstractions.Entities.DbPerson", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("ID");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CREATED");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("CREATED_BY");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DATE_OF_BIRTH");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("longtext")
                        .HasColumnName("E_MAIL_ADDRESS");

                    b.Property<string>("FirstName")
                        .HasColumnType("longtext")
                        .HasColumnName("FIRST_NAME");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext")
                        .HasColumnName("LAST_NAME");

                    b.Property<string>("MiddleName")
                        .HasColumnType("longtext")
                        .HasColumnName("MIDDLE_NAME");

                    b.Property<Guid>("SexId")
                        .HasColumnType("char(36)")
                        .HasColumnName("SEX");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("MODIFIED");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("MODIFIED_BY");

                    b.HasKey("Id");

                    b.HasIndex("SexId");

                    b.ToTable("people");
                });

            modelBuilder.Entity("EGM.GQL.DataAccess.Abstractions.Entities.DbSex", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("ID");

                    b.Property<string>("Description")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("DESCRIPTION");

                    b.Property<string>("ShortDescription")
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)")
                        .HasColumnName("SHORT_DESCRIPTION");

                    b.HasKey("Id");

                    b.ToTable("sex");
                });

            modelBuilder.Entity("EGM.GQL.DataAccess.Abstractions.Entities.DbPerson", b =>
                {
                    b.HasOne("EGM.GQL.DataAccess.Abstractions.Entities.DbSex", "Sex")
                        .WithMany()
                        .HasForeignKey("SexId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sex");
                });
#pragma warning restore 612, 618
        }
    }
}
